"""add profile photo

Revision ID: 529bf1e730e3
Revises: 38f86a07f483
Create Date: 2025-12-06 18:28:44.263294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529bf1e730e3'
down_revision = '38f86a07f483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
